services:
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    repo: https://github.com/your-username/ecommerce-full
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: your-actual-mongodb-uri
      - key: JWT_SECRET
        value: your-jwt-secret